### ISSUE TITLE
ORCMD - Inventory Gathering - Missing to log "Primary key" & "ctime" fields in ORCMD

### ISSUE THREAD

**Issue by piniguez** [open-mpi/orcm#101]
ORCMD is not logging "Primary key" & "ctime" fields when sensor_base_collect_inventory parameter is enabled. These fields are standarized as part of the ORCMD log format to simplify automated validation. See current output example:

***** INCORRECT OUTPUT: () **********
[pedro@centospedro demo]$ /home/pedro/orcm-internal/bin/orcmd -s /home/pedro/sensors/demo/orcm-site.xml -omca sensor dmidata -omca sensor_base_collect_inventory true
[centospedro:23402] 
******************************
Thu Jan  8 12:36:22 2015: ORCM version: 1.0.0a1 AGGREGATOR: [[0,0],1] started and connected to AGGREGATOR: [[0,0],0]
******************************
DB request: update_node_features; data:
hostname=centospedro,bb_vendor=Intel Corporation,bb_model=S5520SC,bb_version=E30682-355,bios_vendor=Intel Corp.,bios_version=S5500.86B.01.X2.0059.091520111722,bios_release_date=09/15/2011,cpu_vendor=GenuineIntel,cpu_family=6,cpu_model_number=44,cpu_model=Intel(R) Xeon(R) CPU           X5680  @ 3.33GHz

***** CORRECT OUTPUT: (sensors) **********
[pedro@centospedro demo]$ /home/pedro/orcm-internal/bin/orcmd -s /home/pedro/sensors/demo/orcm-site.xml -omca sensor heartbeat,coretemp
[centospedro:23266] 
******************************
Thu Jan  8 12:34:40 2015: ORCM version: 1.0.0a1 AGGREGATOR: [[0,0],1] started and connected to AGGREGATOR: [[0,0],0]
******************************
DB request: store; data:
primary_key=coretemp,ctime=2015-01-08 12:34:45-0600,hostname=centospedro,core 0=35.000000:degrees C,core 1=29.000000:degrees C,core 2=30.000000:degrees C,core 3=31.000000:degrees C,core 4=30.000000:degrees C,core 5=28.000000:degrees C,core 6=29.000000:degrees C,core 7=30.000000:degrees C,core 8=27.000000:degrees C,core 9=25.000000:degrees C,core 10=31.000000:degrees C,core 11=32.000000:degrees C

**Comment by vpedabal** [comment]
I can give a bit of leeway for the timestamp (although it is not part of the original requirements) but I cannot agree to adding the primary key here. Every item logged under update_node_feature must be treated as an inventory collection 'irrespective' of which component is logging it.

I understand the sensor metrics were logging with a primary key, but that is because different sensor metrics can have values logged under the same 'keys' like the "core IDs". But for inventory irrespective of the component collecting the key, the value MUST be the same, this should be one of the validation test cases. So for e.g., bb_serial when collected as part of the dmidata plugin or the IPMI plugin must correspond to the same value.

Eventually when the database APIs are updated to have a single store procedure across all components & data storage types, We may have a unique identifier for each type of store procedure - inventory, sensor_metrics, etc. @avilcheslopez can work with you on providing what might change for the print db plugin with the new APIs.

Please let me know if you have any concerns with this, but if not, I'll just add the time stamp and resolve the issue.

**Comment by piniguez** [comment]
Thanks for the detailed explanation Vineet. No concerns at all, I am agree with your comments above.
