### ISSUE TITLE
ORCM CLI/Job Launch tools --help shows non-posix switches.

### ISSUE THREAD

**Issue by noahv** [open-mpi/orcm#107]
Decision was to no longer document non-posix switches.  For example, ocli --help shows both "-gomca" and "--gomca".

This should just be "--gomca".

**Comment by lrrajesh** [comment]
This is not high priority we will fix this for next release. Documentation should mention the posix  style options only.

**Comment by benmcclelland** [comment]
The fix for this would require and upstream change from openmpi which they have said would have too much impact on current user base to change.  We determined in the last meeting about this to just have documentation reflect POSIX style.  We will need to make an exception for help messages for the following:

   -am <arg0>            Aggregate MCA parameter set file list
   -gomca|--gomca <arg0> <arg1>  
                         Pass global MCA parameters that are applicable to
                         all contexts (arg0 is the parameter name; arg1 is
                         the parameter value)
   -omca|--omca <arg0> <arg1>  
                         Pass context-specific MCA parameters; they are
                         considered global if --gomca is not used and only
                         one context is specified (arg0 is the parameter
                         name; arg1 is the parameter value)

I suggest we mark this as a wontfix

**Comment by vpedabal** [comment]
Can we change the help menu by removing the reference to -gomca or -omca, etc?

**Comment by benmcclelland** [comment]
The change would be needed in opal/mca/base/mca_base_cmd_line.c which is an ompi file.  The ompi guys have said that they wouldn't accept this change upstream.  I suggest we leave these options alone and just leave them out of the wiki docs.
