### ISSUE TITLE
osub accepts an incorrect values as number of nodes as parameter

### ISSUE THREAD

**Issue by vlopezsantoyo** [open-mpi/orcm#134]
osub creates a session even though an incorrect number of nodes was passed as parameter:

node 0:
```
[victor@karate cli-tools]$ osub --node 0  -b runjobs.sh
RECEIVED ALLOC ID 1
```

node -1:
```
[victor@karate cli-tools]$ osub --node -1  -b runjobs.sh
RECEIVED ALLOC ID 2
```

More nodes than nodes available:
```
[victor@karate cli-tools]$ osub --node 30  -b runjobs.sh
RECEIVED ALLOC ID 3
```

The question is if it is OK for osub to accept such a parameters and try to allocate a session with them. At least for the parameters like 0 or negative ones, an error should be prompt.

The session will not be created and in case of the allocation of more resources than available, this will be known until the status of the queue is queried through ocli/octl:

```
[victor@karate cli-tools]$ ocli queue status
********
QUEUES
********
running (0 sessions)
----------
hold (1 sessions)
----------
3       500|500 30      EX      B       session exceeds resources
default (0 sessions)
```
Also, the command always return 0 which prevent to rely on the return code to verify if the session was allocated correctly. This issue is already filed here: https://github.com/open-mpi/orcm/issues/105

**Comment by benmcclelland** [comment]
I can certainly fix the 0 and negative cases.  The other case where we exceed available resources is simple in this case, but could easily get very complicated in the future.  For example maybe we start adding in power, memory, etc as other resources to be defined. I'm not sure we want the scheduler to stop what its doing to look at every request that comes in to verify that it could be eventually satisfied in order to pass back an immediate return code.  This doesn't seem like it would scale very well with a high number of session requests and resource constraints.  The hold queue is exactly for that (for now) for when the scheduler has a chance to look at the request and decide that the resource constraints can't be met.

**Comment by vpedabal** [comment]
The first part of this issue will be fixed for the release, but the second part needs to be addressed at a later point.

**Comment by vlopezsantoyo** [comment]
I have verified that the issue regarding nodes<=0 is not longer present in v0.7 branch, git:3bbd2159a1b039dac0c6dfa12c15894c84593890

A number of nodes greater than available nodes won't be fixed
