### ISSUE TITLE
About SIGAR´s usage for computing component cpu_user, cpu_sys and cpu_idle metrics

### ISSUE THREAD

**Issue by forzaclaudio** [open-mpi/orcm#137]
Just to make sure I understand the way some of the metrics are computed:

At time t_0:
ORCM computes cpu_user as the sum of user and nice values contained in a SIGAR´s struct i.e. sigar_cpu_t struct

>cpu_user = user + nice 
cpu_sys = sys + wait
cpu_idle 

in the same call, you store the values into the **pcpu** struct for future use in the next call to ORCM´s function **sigar_collect_cpu**. where my guess is that the "p" prefix stands for previous cpu values.

then at time t_1
You get a new set of values from sigar and do the same
>cpu_user = user + nice 
cpu_sys = sys + wait
cpu_idle 

the cpu metrics are rely on the difference in values of cpu_user, cpu_sys and cpu_idle at both ends of the interval of time between t_0 and t_1. To compute the final metric you normalise, i.e. divide, by the difference of total_value at times t0 and t1 which is stored in cpu_diff and multiply by 100 in order to obtain a percentage. See [sigar_collect_cpu function on line 328 here!](https://github.com/open-mpi/orcm/blob/61d4eff5e406342f685b63a2567d5a630b7b3bfb/orcm/mca/sensor/sigar/sensor_sigar.c)

So if the time between the t0 and t1 is 5 seconds i.e. ORCM's default sampling rate, then it is implicit that the % reported for cpu_user, cpu_sys and cpu_idle is over an interval of 5 seconds. If ORMC's sampling rate rate is changed to 1 second then the I would be getting the % over 1 second.
Therefore, if I ask ORCM for a sampling frequency of 60 seconds this would mean that the metrics logged represent the percentage over a 1 minute period. 

1. My first question is whether my assumption that t0 and t1 is  related with ORCM's sampling rate is right?
2. In case the above is not true, is the time between t0 and t1 always constant?, in such a case what's the value of this time. 1 sec? 1 msec? 25 um? 
3. Finally, I would expect that ORCM logged some sort of "instantaneous" cpu_user, cpu_sys, cpu_idle percentage, independently of sampling rate.

**Comment by forzaclaudio** [comment]
Moreover, I checked whether **sigar_cpu_t.total** changes over time using different sampling times and from this test, it seems that we should expect it to be constant over time
![sigar cpu_total](https://cloud.githubusercontent.com/assets/8369713/5804753/2cb3a620-9fce-11e4-940d-2898425f0ca8.png)
**Figure 1** Value of SIGA's sigar_cpu_t.total when sampled every 5 seconds during 60 seconds
![sigar cpu_total2](https://cloud.githubusercontent.com/assets/8369713/5804899/9c4e7450-9fcf-11e4-945f-0a1ce3d2ab6b.png)
**Figure 2** Value of SIGA's sigar_cpu_t.total when sampled every 1 seconds during 60 seconds

So no matter at what time we compute 
> cpu_diff = (double)(cpu.total - pcpu.total);

the result should be cero and anything divided by cpu_diff it should diverge!

> tmp = (float)((cpu.user - pcpu.user) * 100.0 / cpu_diff) + (float)((cpu.nice - pcpu.nice) * 100.0 / cpu_diff);

**Comment by vpedabal** [comment]
Answers to your questions:
1. Yes, you are (almost) correct, the time delta is directly related to the sampling rate, however due to some other interference in the OS the sampling interval could be off by a few uSeconds, which will affect our calculation of cpu utilization %ages.
2. The above case is true, the time between t0 and t1 is directly related to the sampling rate, albeit minor interference in the OS.
3. We can indeed log an instantaneous cpu_user, cpu_sys, cpu_idle but it wouldn't give us any significant value, other than detecting spikes, at the --exact-- same time of sampling, which in my opinion is unlikely to happen. If the spikes persist for more than two sample points then it will get detected and recorded in the current format.

cpu.total contains the --TOTAL-- time spent by the CPU on user, user(nice), sys, idle, wait, irq, soft_irq, stolen. For details of each parameter refer to the proc/stat man page.

cpu_diff in this context gives the total time spent by the CPU from the previous sample to the current sample. Since the sampling rate is uniform, the cpu_diff will also remain very close

Dividing the delta of time spent by the CPU on user/system/idle states, with the cpu_diff will give us the ratio of time spent by the CPU in each state. Multiplying with 100 gives you the %age of time spent.

Does this explanation clear it up?

**Comment by forzaclaudio** [comment]
Indeed, thanks for taking the time to address the questions.
